version: '3.4'

services:
  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: .
      dockerfile: FrontEnd/Dockerfile
    ports:
      - "40001:50001"
  frontend-dapr:
    image: "daprio/daprd:latest"
    command:
      [
        "./daprd",
        "-app-id",
        "FrontEnd",
        "-app-port",
        "8080",
        "-components-path",
        "/components"
      ]
    depends_on:
      - frontend
    network_mode: "service:frontend"
    volumes:
      - "./dapr/components/:/components"
  
  backend:
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: .
      dockerfile: BackEnd/Dockerfile
  backend-dapr:
    image: "daprio/daprd:latest"
    command:
      [
        "./daprd",
        "-app-id",
        "BackEnd",
        "-app-port",
        "8080",
        "-components-path",
        "/components"
      ]
    depends_on:
      - backend
    network_mode: "service:backend"
    volumes:
      - "./dapr/components/:/components"

  backend1:
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: .
      dockerfile: BackEnd/Dockerfile
  backend1-dapr:
    image: "daprio/daprd:latest"
    command:
      [
        "./daprd",
        "-app-id",
        "BackEnd",
        "-app-port",
        "8080",
        "-components-path",
        "/components"
      ]
    depends_on:
      - backend1
    network_mode: "service:backend1"
    volumes:
      - "./dapr/components/:/components"

  daprsubdemo:
    image: ${DOCKER_REGISTRY-}daprsubdemo
    build:
      context: .
      dockerfile: DaprSubDemo/Dockerfile
  daprsubdemo-dapr:
    image: "daprio/daprd:latest"
    command:
      [
        "./daprd",
        "-app-id",
        "daprsubdemo",
        "-app-port",
        "8080",
        "-components-path",
        "/components"
      ]
    depends_on:
      - daprsubdemo
    network_mode: "service:daprsubdemo"
    volumes:
      - "./dapr/components/:/components"

  identity:
    image: ${DOCKER_REGISTRY-}identity
    build:
      context: .
      dockerfile: Identity/Dockerfile
  identity-dapr:
    image: "daprio/daprd:latest"
    command:
      [
        "./daprd",
        "-app-id",
        "identity",
        "-app-port",
        "8080",
        "-components-path",
        "/components"
      ]
    depends_on:
      - identity
    network_mode: "service:identity"
    volumes:
      - "./dapr/components/:/components"

  dapridentity:
    image: ${DOCKER_REGISTRY-}dapridentity
    build:
      context: .
      dockerfile: DaprIdentity/Dockerfile
    ports:
      - "5112:8080"
  dapridentity-dapr:
    image: "daprio/daprd:latest"
    command:
      [
        "./daprd",
        "-app-id",
        "dapridentity",
        "-app-port",
        "8080",
        "-components-path",
        "/components"
      ]
    depends_on:
      - dapridentity
      - identity-database
    network_mode: "service:dapridentity"
    volumes:
      - "./dapr/components/:/components"

  identity-database:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
    - "1433:1433"
    environment:
    - SA_PASSWORD=longchi@123
    - ACCEPT_EULA=Y